name: Scrape Formula One News

on:
  workflow_dispatch:

  repository_dispatch:
    types:
      - webhook

  schedule:
    - cron: '0 0 * * *'
    - cron: '0 6 * * *'
    - cron: '0 15 * * *'

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: pnpm/action-setup@v2
        with:
          version: 7.18.2
          run_install: true
      - run: |
          pnpm run scrape news
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com
          git diff --quiet && git diff --staged --quiet || git commit -am "[bot] update news Formula Fan database"
          git push origin main